// Simple test script to verify environment variables
console.log('Testing environment variables...');

// Simulate Vite environment variables
const env = {
  VITE_USE_GCS: process.env.VITE_USE_GCS || 'false',
  VITE_GCS_PROXY_URL: process.env.VITE_GCS_PROXY_URL || 'http://localhost:3001',
  // Primary Appwrite Server (working database server)
  VITE_APPWRITE_ENDPOINT: process.env.VITE_APPWRITE_ENDPOINT || 'https://fra.cloud.appwrite.io/v1',
  VITE_APPWRITE_PROJECT_ID: process.env.VITE_APPWRITE_PROJECT_ID || '68ca9e8e000ddba95beb',
  VITE_APPWRITE_DATABASE_ID: process.env.VITE_APPWRITE_DATABASE_ID || '68ca9f760003f35cf8ca',
  VITE_APPWRITE_COLLECTION_ID: process.env.VITE_APPWRITE_COLLECTION_ID || 'qrcode',
  VITE_APPWRITE_STORAGE_BUCKET_ID: process.env.VITE_APPWRITE_STORAGE_BUCKET_ID || '68caacec001fd1ff6b9d',
  // First Fallback Appwrite Server (new server with more storage)
  VITE_APPWRITE_FALLBACK_ENDPOINT: process.env.VITE_APPWRITE_FALLBACK_ENDPOINT || 'https://fra.cloud.appwrite.io/v1',
  VITE_APPWRITE_FALLBACK_PROJECT_ID: process.env.VITE_APPWRITE_FALLBACK_PROJECT_ID || '68ccc43b0039d53b4ccd',
  VITE_APPWRITE_FALLBACK_STORAGE_BUCKET_ID: process.env.VITE_APPWRITE_FALLBACK_STORAGE_BUCKET_ID || '68ccc46c001ef5e9ef03',
  // Second Fallback Appwrite Server (additional storage)
  VITE_APPWRITE_SECOND_FALLBACK_ENDPOINT: process.env.VITE_APPWRITE_SECOND_FALLBACK_ENDPOINT || 'https://fra.cloud.appwrite.io/v1',
  VITE_APPWRITE_SECOND_FALLBACK_PROJECT_ID: process.env.VITE_APPWRITE_SECOND_FALLBACK_PROJECT_ID || '68ccc7cb003ae8c6d892',
  VITE_APPWRITE_SECOND_FALLBACK_STORAGE_BUCKET_ID: process.env.VITE_APPWRITE_SECOND_FALLBACK_STORAGE_BUCKET_ID || '68ccc7df00229b45d257',
  // Third Fallback Appwrite Server (even more storage)
  VITE_APPWRITE_THIRD_FALLBACK_ENDPOINT: process.env.VITE_APPWRITE_THIRD_FALLBACK_ENDPOINT || 'https://fra.cloud.appwrite.io/v1',
  VITE_APPWRITE_THIRD_FALLBACK_PROJECT_ID: process.env.VITE_APPWRITE_THIRD_FALLBACK_PROJECT_ID || '68ccc9900006d14e2952',
  VITE_APPWRITE_THIRD_FALLBACK_STORAGE_BUCKET_ID: process.env.VITE_APPWRITE_THIRD_FALLBACK_STORAGE_BUCKET_ID || '68ccca1700357009547c'
};

console.log('VITE_USE_GCS:', env.VITE_USE_GCS);
console.log('VITE_GCS_PROXY_URL:', env.VITE_GCS_PROXY_URL);
console.log('--- PRIMARY APPWRITE SERVER (Database & Storage) ---');
console.log('VITE_APPWRITE_ENDPOINT:', env.VITE_APPWRITE_ENDPOINT);
console.log('VITE_APPWRITE_PROJECT_ID:', env.VITE_APPWRITE_PROJECT_ID);
console.log('VITE_APPWRITE_DATABASE_ID:', env.VITE_APPWRITE_DATABASE_ID);
console.log('VITE_APPWRITE_COLLECTION_ID:', env.VITE_APPWRITE_COLLECTION_ID);
console.log('VITE_APPWRITE_STORAGE_BUCKET_ID:', env.VITE_APPWRITE_STORAGE_BUCKET_ID);
console.log('--- FIRST FALLBACK APPWRITE SERVER (Storage Only) ---');
console.log('VITE_APPWRITE_FALLBACK_ENDPOINT:', env.VITE_APPWRITE_FALLBACK_ENDPOINT);
console.log('VITE_APPWRITE_FALLBACK_PROJECT_ID:', env.VITE_APPWRITE_FALLBACK_PROJECT_ID);
console.log('VITE_APPWRITE_FALLBACK_STORAGE_BUCKET_ID:', env.VITE_APPWRITE_FALLBACK_STORAGE_BUCKET_ID);
console.log('--- SECOND FALLBACK APPWRITE SERVER (Storage Only) ---');
console.log('VITE_APPWRITE_SECOND_FALLBACK_ENDPOINT:', env.VITE_APPWRITE_SECOND_FALLBACK_ENDPOINT);
console.log('VITE_APPWRITE_SECOND_FALLBACK_PROJECT_ID:', env.VITE_APPWRITE_SECOND_FALLBACK_PROJECT_ID);
console.log('VITE_APPWRITE_SECOND_FALLBACK_STORAGE_BUCKET_ID:', env.VITE_APPWRITE_SECOND_FALLBACK_STORAGE_BUCKET_ID);
console.log('--- THIRD FALLBACK APPWRITE SERVER (Storage Only) ---');
console.log('VITE_APPWRITE_THIRD_FALLBACK_ENDPOINT:', env.VITE_APPWRITE_THIRD_FALLBACK_ENDPOINT);
console.log('VITE_APPWRITE_THIRD_FALLBACK_PROJECT_ID:', env.VITE_APPWRITE_THIRD_FALLBACK_PROJECT_ID);
console.log('VITE_APPWRITE_THIRD_FALLBACK_STORAGE_BUCKET_ID:', env.VITE_APPWRITE_THIRD_FALLBACK_STORAGE_BUCKET_ID);

console.log('USE_GCS evaluation:', env.VITE_USE_GCS === 'true');